# Generated by Django 4.2.3 on 2023-08-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
